### ISSUE TITLE
Screenshots are not displayed correctly

### ISSUE THREAD

**Issue by ferpasri** [TESTARtool/TESTAR_dev#105]
By disabling all the notepad buttons, leaving only the text field and running about one hundred actions, this issue can be observed using the View mode of TESTAR or using the desktop_simple_stategraph protocol (with the html report).

Sometimes the screenshot of the state that transits from an action performed is not shown correctly in these captures.

![state1](https://user-images.githubusercontent.com/32359126/43453443-6f90b37c-94ba-11e8-815f-d6f5012090a5.PNG)

Current status: we have the text "161541072" in the field
We perform action: Type text "-1408540088"
New state to observe: we have the text "-1408540088" in the field

However, a capture of another different state is shown:
![state2](https://user-images.githubusercontent.com/32359126/43453779-36ff2650-94bb-11e8-9b13-6c3301460931.PNG)

Investigate if it occurs only with the text input fields or also with other widgets

**Comment by pekkakaho** [comment]
The first screenshot might have a bug:

Tag:ScreenshotPath=null\null\SC1mc3nxk158954590551.png

**Comment by pekkakaho** [comment]
The nulls in path happen with Spy-mode

**Comment by carlosengers** [comment]
As discovered during a test run at 2019-03-25 with the graph database:

One of the screenprints (concretestate #77:2) did not capture the SUT, but captured the background: SUT  was already stopped. This does not seem a graph database issue. 

First preliminary feedback of Fernando on 27-3:

In this particular case:
transitions
<edge id="#66:2" source="#80:1" target="#79:0"> lot of properties - Close Action <edge id="#67:2" source="#79:0" target="#77:2"> few properties

Are causing an error into

node: # 77:2
StateID: "SCC000"
Verdict: severity: 0.99999999 info: System is offline! I assume it crashed!
And the image that you comment.
 
'evidence'
[testarscreenprints.zip](https://github.com/TESTARtool/TESTAR_dev/files/3162135/testarscreenprints.zip)
[graphml.zip](https://github.com/TESTARtool/TESTAR_dev/files/3162137/graphml.zip)

**Comment by pekkakaho** [comment]
has been fixed
