### ISSUE TITLE
[Refactor] Multiple edit actions generated for a single editable widget (e.g. text box)

### ISSUE THREAD

**Issue by pekkakaho** [TESTARtool/TESTAR_dev#114]
This is maybe unwanted behaviour instead of a bug, but it messes up the action selection, because random chance of selecting editable widgets is much higher than clickable widgets.

TESTAR generates multiple edit actions with different text for each editable widget, for example text box.

A better behaviour would be generating one edit action for each editable widget, then generating the input for the edit if it is selected, or just generating one input for the action.

**Comment by pekkakaho** [comment]
The text input functionality has been party refactored, but the random input generation is the same. The random input generation can be overwritten in protocol, it is separated from the action.

Did not find that TESTAR would generate multiple actions for single text input widget.

**Comment by ferpasri** [comment]
In CodingManager class we're using action.toString() to build the differents ActionsID.

This action.toString() contains this description:

Compound Action =
Compound Action =
Move mouse to (975.0, 468.0).
Press Mouse Button BUTTON1
Release Mouse Button BUTTON1
Press Key VK_CONTROL
Press Key VK_A
Release Key VK_A
Release Key VK_CONTROL
Type text '1356375942'

Where this Type text is chosen randomly between the texts of es.upv.staq.testar.managers.DataManager.java class

This is why we have multiple actions for single text input widget.

If we create a CustomActionID with something like action.get(Tags.TargetID), we can obtain only one action per text input widget.
