### ISSUE TITLE
Image recognition + visualization = issues

### ISSUE THREAD

**Issue by pekkakaho** [TESTARtool/TESTAR_dev#129]
When turning TESTAR visualization on (green and red dots), the image recognition fails to find the action, at least the first action after turning the visualization on.

Not much we can do about that, unless we can take new pics of the buttons after turning on the visualization.

**Comment by ferpasri** [comment]
Check the status of the [widget recognition protocols](https://github.com/TESTARtool/TESTAR_dev/blob/master/testar/resources/settings/desktop_widget_recognition/Protocol_desktop_widget_recognition.java) to determine if this issue persists and how to change the Spy painting order to remove the dots before taking the screenshot of the widget.

**Comment by ferpasri** [comment]
This was fixed in #395 

To avoid TESTAR taking widgets screenshots containing green and red dots when the visualization is on, we clear the canvas just before taking the screenshot
