### ISSUE TITLE
no sequence prints of error box in view modus

### ISSUE THREAD

**Issue by mdeiman** [TESTARtool/TESTAR_dev#137]
In View modus you never not see (error) boxes.
After left click on "=" in buggy calc you get a window. But you do not see it in view mode.

![schermafbeelding 2018-11-09 om 14 46 37](https://user-images.githubusercontent.com/34946629/48266150-d51ee380-e42e-11e8-9eb5-f192375b16fd.png)

**Comment by mdeiman** [comment]
Any progress on this topic?

**Comment by mdeiman** [comment]
Any progress on this issue?

**Comment by ferpasri** [comment]
The view mode was changed to the HTML report.
In the current TESTAR master version, the tool takes a screenshot of the desktop if a failure is detected.
