### ISSUE TITLE
Wrong green dots in Spy mode

### ISSUE THREAD

**Issue by mdeiman** [TESTARtool/TESTAR_dev#144]
In de buggy calc wrong green dots. Two dots for backspace and green dots between buttons.
![schermafbeelding 2018-11-18 om 20 27 13](https://user-images.githubusercontent.com/34946629/48677200-466a3f00-eb71-11e8-8409-10deb8ff9d06.png)

**Comment by ferpasri** [comment]
Solved.
Now these Panels and Menu items of the SUTs should not have an action associated.

**Comment by GuyT07** [comment]
Could you please add the commit where this has been fixed?

**Comment by ferpasri** [comment]
https://github.com/TESTARtool/TESTAR_dev/commit/5707ce51de1161cfa99f554e8eb58c020d355def#diff-0e69ff38354ef2fe90f07fccc5d17cba
