### ISSUE TITLE
[Record mode] User actions not always captured correctly

### ISSUE THREAD

**Issue by pekkakaho** [TESTARtool/TESTAR_dev#146]
Sometimes user actions are not captured correctly, for example pushing close-button in the upper right corner of the SUT is not always captured.

**Comment by ferpasri** [comment]
The State of the SUT is constantly updating while we are waiting for a userEvent  (DefaultProtocol -> waitUserActionLoop).

Sometimes after an action, the SUT & the States changes and when we try to find the widget of the executed action, we're looking in the wrong widget tree.

Increase the refresh time of the State?
Update the State only if a specific keyboard button was used by the user? without save the action?

**Comment by pekkakaho** [comment]
The issue still exists if the user is doing actions fast during Record-mode.

**Comment by Nigel-Steijn** [comment]
## What do I see?
Most of the actions in record mode are not registered.

## What do I expect?
I expect that each button I pressed in the record mode will be played back in replay mode.

## What did we do?
I recorded a sequence of keypresses, which I want to save to replay later on.

We have also tested this with a 10-second delay between each key-input, but we get the same results.

We have tested it on different hardware configurations.

The processor I use is an Intel Core i9 10900k at 4.88GHz; the same result occurs on the lower-end hardware.

## Example
(Default settings, changed the Chrome driver and website)
https://youtu.be/GsNGEKKo9JE

## Additional remarks
Enabling `Use Recorded Action Timing During Replay` does not fix this.
Protocol and SUT connector settings are not set to the correct values after loading a sequence.

I wouldn't expect this to be much of a performance issue.
Is this an issue that will be solved soon? At this moment, we are kind of stuck on it.

Let me know if you need anything else!

**Comment by ferpasri** [comment]
NOTE: Record mode was disabled from TESTAR
