### ISSUE TITLE
Select List web element is not recognized correctly with IExplorer

### ISSUE THREAD

**Issue by ferpasri** [TESTARtool/TESTAR_dev#149]
https://developer.mozilla.org/es/docs/Web/HTML/Elemento/select

The select> element is used to create a drop-down list.
select name="select">
  option value="value1">Value 1/option> 
  option value="value2" selected>Value 2/option>
  option value="value3">Value 3/option>
/select>

Internet Explorer:
The container element of the list is recognized, but when it is open TESTAR doesn't detect the child elements.
Using the Windows inspect.exe application, I have seen that the list is created in the OS but not like a part of the web page. Instead, it is created as a new descent list from the desktop.

Chrome:
With Chrome it has a strange behavior, detects the elements of the list but they are all overlaped with each other in the parent container.

Firefox:
Works fine with Firefox

**Comment by ferpasri** [comment]
This element is detected if TESTAR runs and make a widget tree with multiple processes (iexplore.exe)

**Comment by pekkakaho** [comment]
Support for multiple processes has been implemented, but it has not been merged. Probably a generic solution should be implemented.

**Comment by pekkakaho** [comment]
#68 duplicate
