### ISSUE TITLE
Restore test.settings and protocol.settings files

### ISSUE THREAD

**Issue by ferpasri** [TESTARtool/TESTAR_dev#154]
If the user or TESTAR :) ,deletes or changes the test.settings files of the different settings protocols accidentally, TESTAR should offer some way of restoring the settings file with default options.

This may be interesting for users who work with TESTAR distributions and they don't usually use the download and compilation of the program.

If the protocol is deleted, TESTAR create an empty org.fruit.monkey.DefaultProtocol file into setting folder.

**Comment by pekkakaho** [comment]
Creating new protocols should be made easier (through the Settings Dialog of TESTAR)

**Comment by ferpasri** [comment]
If some settings are deleted from test.settings file:
- TESTAR uses default settings values
- TESTAR restores those default values in the test.settings file

For future work, we will need to track with specific issues if needed
