### ISSUE TITLE
Java Swing - Clickable items not recognized

### ISSUE THREAD

**Issue by mdeiman** [TESTARtool/TESTAR_dev#157]
In a SUT are some menu-items and buttons for closing and minimize a window  not recognized.
![schermafbeelding 2019-02-28 om 11 40 14](https://user-images.githubusercontent.com/34946629/53564919-650ca880-3b58-11e9-9203-58d473c89dc0.png)
![schermafbeelding 2019-02-28 om 11 30 00](https://user-images.githubusercontent.com/34946629/53564989-92f1ed00-3b58-11e9-9c25-de2a0a09d340.png)

![schermafbeelding 2019-02-28 om 11 14 34](https://user-images.githubusercontent.com/34946629/53565245-35aa6b80-3b59-11e9-8142-28bb875825d8.png)

**Comment by ferpasri** [comment]
First image:

JInternalFrame component, not sure which kind of components are those min, max and close buttons.
Are they childrens of this JInternalFrame?
Not allowed properties by AccessBridge?

**Comment by mdeiman** [comment]
Is that a question for me? I don't know.

**Comment by mdeiman** [comment]
In the third image menu item Wise Client Clipboard and Over dit programma isn't recognized.

**Comment by ferpasri** [comment]
Third image menu item should already be solved into "java_swing_dev" branch

I'm not sure how to solve the recognition of the "elements" of the first image.

**Comment by mdeiman** [comment]
The  up and the down button are not recognized by Testar. 
Up increase the number bij 1 and down decrease the number by 1.
![schermafbeelding 2019-03-07 om 14 45 14](https://user-images.githubusercontent.com/34946629/53962682-fb5a4480-40eb-11e9-8b96-1960317da105.png)

**Comment by mdeiman** [comment]
Oke. Close button etc are recognized now. First image.
