### ISSUE TITLE
[Java Swing] Not clickable items are clickable for Testar

### ISSUE THREAD

**Issue by mdeiman** [TESTARtool/TESTAR_dev#158]
Not clickable items (grey items) are clickable for Testar.
![schermafbeelding 2019-02-26 om 18 52 01](https://user-images.githubusercontent.com/34946629/53565445-d26d0900-3b59-11e9-95d1-484b6ce9493c.png)

**Comment by ferpasri** [comment]
This should already be solved into "java_swing_dev" branch

**Comment by ferpasri** [comment]
Zip with java_swing_dev version
https://drive.google.com/open?id=1huOsMgAcwbIqrvyujgRHUGkmh6PzT2eY

**Comment by mdeiman** [comment]
This is unfortunately not solved in de java_swing_dev version

**Comment by mdeiman** [comment]
This is okay now in de java_swing_dev branch!
