### ISSUE TITLE
Filtering Protocol - Focus outside the application

### ISSUE THREAD

**Issue by mdeiman** [TESTARtool/TESTAR_dev#159]
During click feature enabled the focus is outside the application. Redbox around the screen blinking.

![schermafbeelding 2019-03-04 om 10 49 25](https://user-images.githubusercontent.com/34946629/53725281-fbe4a800-3e6b-11e9-97d9-d0767d7c40bf.png)

**Comment by ferpasri** [comment]
I have also reproduced it with the notepad, I indicate it as a general error of the filtering protocol

**Comment by mdeiman** [comment]
Should this be solved now? I do not see the issue anymore. We could then close it.
