### ISSUE TITLE
Java Swing - Strange green dots during Generate Mode

### ISSUE THREAD

**Issue by mdeiman** [TESTARtool/TESTAR_dev#160]
During generate, using shift up, strange green dots and tekst in window.
![schermafbeelding 2019-03-04 om 11 21 17](https://user-images.githubusercontent.com/34946629/53731203-4b31d500-3e7a-11e9-83f3-db7e4ab35281.png)

**Comment by mdeiman** [comment]
Also in this screen several green dots (en red dot) which are not clickable, but are clickable for Testar.

![schermafbeelding 2019-03-05 om 12 40 40](https://user-images.githubusercontent.com/34946629/53803392-e1cac880-3f44-11e9-9c1b-4085f0b7147a.png)

**Comment by ferpasri** [comment]
Image n1:
Overlapped panels and widgets are not filtered properly.
TESTAR is showing the widgets of the background panels.

**Comment by mdeiman** [comment]
Solved.
