### ISSUE TITLE
[Spy mode]  The id of State is changing

### ISSUE THREAD

**Issue by mdeiman** [TESTARtool/TESTAR_dev#161]
In Spy mode the Id's of the state is changing all the time between two identifications. 
It's blinking.

This is for all states.

![schermafbeelding 2019-03-04 om 13 39 03](https://user-images.githubusercontent.com/34946629/53734005-edee5180-3e82-11e9-80b0-8242fd90aa62.png)
![schermafbeelding 2019-03-04 om 13 37 57](https://user-images.githubusercontent.com/34946629/53734012-f050ab80-3e82-11e9-9143-6f50564e46e9.png)

**Comment by ferpasri** [comment]
It seems that the text "LESSSYSTEM" appears and disappears in the Title of the SUT.
This causes the existence of two widgets, one with that text and the other without the text in the Title property.
Therefore, the State Identificator constantly changes, including or not "LESSSYSTEM" text like a property.

**Comment by ferpasri** [comment]
Changing the ID due to the changed Title is not a bug but a confusing aspect of Spy mode for users.
The development from #220 will allow users to customize displayed properties.

**Comment by ferpasri** [comment]
The ID of the state was changing due to the dynamic Title property.
This is the expected behavior of the State ID calculation but a dynamic aspect of the SUT.
