### ISSUE TITLE
Java Swing -  Date window clickable items not recognized

### ISSUE THREAD

**Issue by mdeiman** [TESTARtool/TESTAR_dev#164]
In the date windows in the Wise application are clickable items not recognized. Green dots on a strange place.

![schermafbeelding 2019-03-08 om 12 17 09](https://user-images.githubusercontent.com/34946629/54027233-0d49ef00-41a1-11e9-8658-029d8698c8e7.png)

**Comment by ferpasri** [comment]
I think that kind of calendar element is not a basic swing component.
I'm not sure if it can be detected by Java Access Bridge calls.

**Comment by mdeiman** [comment]
Mostly okay now. ;)
