### ISSUE TITLE
Java Swing - Row items not recognized

### ISSUE THREAD

**Issue by mdeiman** [TESTARtool/TESTAR_dev#165]
Row items in the Wise application are clickable. You can do double click on an item to get a new window. Testar will never get to this window now.

![Schermafbeelding 2019-03-11 om 13 33 12](https://user-images.githubusercontent.com/34946629/54124945-01119c00-4404-11e9-9993-2385b341a259.png)
![Schermafbeelding 2019-03-11 om 13 33 56](https://user-images.githubusercontent.com/34946629/54125112-682f5080-4404-11e9-849a-ee86cbf779ad.png)

**Comment by ferpasri** [comment]
Java Swing Tables elements are correctly recognized with AccessBridge.

Access Bridge recognizes the number of existing childs that form the row items.

But, unfortunately, the Access Bridge API recognizes these row items with "-1" coordinates, width or height.

<img width="666" alt="IssueJTable" src="https://user-images.githubusercontent.com/32359126/56280436-7e6ab380-610a-11e9-9584-e8af9cb840e8.png">

<img width="522" alt="IssueJTableItems" src="https://user-images.githubusercontent.com/32359126/56280447-84609480-610a-11e9-9395-1836a3459179.png">

**Comment by mdeiman** [comment]
Testar doesn't perform a double click to get to the new window of the image.
The/A row is recognized know.

**Comment by mdeiman** [comment]
Looks good now!
