### ISSUE TITLE
Java Swing - Crash Testar Tag Path unavailable

### ISSUE THREAD

**Issue by mdeiman** [TESTARtool/TESTAR_dev#167]
When or after the Wise application is retrieving records, which can take about 60 sec, Testar crashes in Spy mode and starts up again.

When you click the Haal reserveringen' button, Wise wil retrieve the reservations. A few thousands records. During or after Testar always crashes.
NoSuchTagExcepion Tag 'Path' unavailable.

![Schermafbeelding 2019-03-19 om 14 58 49](https://user-images.githubusercontent.com/34946629/54613485-110c2a00-4a5b-11e9-8b9a-48c4d4a2cb28.png)

**Comment by pekkakaho** [comment]
Some of the tags did not have a default value, which caused exceptions. This should have been fixed.
