### ISSUE TITLE
Current key implementation cannot handle all keys

### ISSUE THREAD

**Issue by GuyT07** [TESTARtool/TESTAR_dev#171]
The current KBKeys enum looks like this: 

```
public enum KBKeys
{
  KEY_FIRST(2400, 400),
  KEY_LAST(2402, 402),
  KEY_TYPED(2400, 400),
  KEY_PRESSED(2401, 401),
  ...
```
Mapping JNativeHook keys to a enum is in general a bad idea because it is (nearly) impossible to maintain all the mappings. 

eg. `VK_EXCLAMATION_MARK`(!) or `VK_ASTERISK`(*) would crash TESTAR because no mapping is available. Please notice that both examples can be inserted when generation mode is random. 

Proposal:
 - Remove KBKeys class, it is redundant and error prone;
 - KeyAction requires special attention;
 - Type class (core) should change US-ASCII to UTF-32;
 - A combination of following commits successfully implemented this: 8b48b2651c1072903ee7069f11e1d2ffea84583f , 90ffdb12d841c2fca8b5e9b7871f7d22c6d4fa3c

**Comment by pekkakaho** [comment]
The UTF-32 support is introducing some issues elsewhere in TESTAR, so those need to be fixed before merging.

**Comment by ferpasri** [comment]
Related with https://github.com/TESTARtool/TESTAR_dev/pull/193
To deal with special characters, we have created a PasteText action that allows the use of the system clipboard for inserting special characters.
