### ISSUE TITLE
Available actions

### ISSUE THREAD

**Issue by GuyT07** [TESTARtool/TESTAR_dev#173]
Observed
 - TESTAR does not correctly identify (all) filtered actions. It seems that when a widget has children, by default the vertical middle of that specific widget 'is clickable'. This behaviour is undesirable because it leads to the break out of TESTAR of the SUT. 

Steps to reproduce
 - SUT: Windows/ notepad;
 - Add Save As (.*[sS]ave [aA]s.*) to click filter;
 - Open Spy mode;
 - Click File;
 - There is a green dot just under 'Save As...' but this widget will be identified by TESTAR as clickable. TESTAR will open Save As dialog and is able to act outside of the SUT.

Expected behaviour
 - When a widget has children do not automatically add a click action to the v-align (vertical middle)

**Comment by ferpasri** [comment]
The same problem as in case #144 

For those container widgets, like the UIAmenu, I think we should study the possibility of disabling the association of actions. (too complicated for the user to disable manually)

Then based on the results or problems.
Start to study the implementation of filtering also the parent widget, or not add the action into his vertical middle.

**Comment by ferpasri** [comment]
Updated:

https://github.com/TESTARtool/TESTAR_dev/commit/5707ce51de1161cfa99f554e8eb58c020d355def#diff-0e69ff38354ef2fe90f07fccc5d17cba

if(w.get(Tags.Role, Roles.Widget).toString().equalsIgnoreCase("UIAMenu")){
// filtering out actions on menu-containers (that would add an action in the middle of the menu)

**Comment by GuyT07** [comment]
Great, thanks! I close the issue.
