### ISSUE TITLE
SUT startup time variable does not function as maximum waiting time, but is blocking for startup

### ISSUE THREAD

**Issue by admulders** [TESTARtool/TESTAR_dev#186]
I think the idea of having an SUT start up time setting is for it to function as a maximum waiting time. However, TESTAR will always wait until the maximum waiting time has expired on startup, before it will start testing the SUT.

This is caused by this piece of code in the DefaultProtocol class: (line 1200)

```
//Print info to the user to know that TESTAR is NOT READY for its use :-(
String printSutInfo = "Waiting for the SUT to be accessible ...";
double startupTime = settings().get(ConfigTags.StartupTime)*1000;
int timeFlash = (int)startupTime;
			
//Refresh the flash information, to avoid that SUT hide the information
int countTimeFlash = 0;
while(countTimeFlash<timeFlash) {
	FlashFeedback.flash(printSutInfo, 2000);
	countTimeFlash += 2000;
}
```

I think the idea was for this popup to run asynchronously, but it actually blocks.

**Comment by ferpasri** [comment]
Solved in https://github.com/TESTARtool/TESTAR_dev/commit/02526aa29e952be4725ce54b62fe74d3fbb0fc88#diff-3c4e8b1fdbc283fbb3c60ed8f95764e7
