### ISSUE TITLE
Switches not recognized

### ISSUE THREAD

**Issue by mdeiman** [TESTARtool/TESTAR_dev#199]
In OnStage, a program running in a web browser, are switches not recognized.
![Schermafbeelding 2019-07-16 om 14 40 53](https://user-images.githubusercontent.com/34946629/61295400-40982c80-a7d8-11e9-86b9-d753e7fb40c2.png)

**Comment by pekkakaho** [comment]
You were using Web_generic protocol? Windows accessibility API does not work well with web applications. Use Webdriver_generic instead.

**Comment by ferpasri** [comment]
In the current TESTAR master branch version, when a web element is not native and recognized by default, we can use the _ClickableClasses_ settings to derive a click action.

https://github.com/TESTARtool/TESTAR_dev/blob/6007a958999dca3ec724771b6157c119786c691c/testar/resources/settings/webdriver_generic/test.settings#L113-L120
