### ISSUE TITLE
CompoundAction : Tag 'Role' unavailable!

### ISSUE THREAD

**Issue by govertbuijs** [TESTARtool/TESTAR_dev#206]
I'm trying to execute a CompoundAction, but the CodingManager (in updateRoleCounter) correctly throws a `NoSuchTagException`.

I can fix this by setting the `Tags.Role ` with a locally generated `Role.from("CompoundAction")`.
But should that be set in the CompoundAction constructor?

**Comment by ferpasri** [comment]
Thanks, fix updated into the current pull request #205

**Comment by ferpasri** [comment]
Solved and merged into master branch
