### ISSUE TITLE
WebDriver – mouse click is not selected action

### ISSUE THREAD

**Issue by Blauwtipje** [TESTARtool/TESTAR_dev#218]
**Description**
The mouse cursor click (and position) is not the same as the selected action (red button in SPY mode when running or look at screenshots in report).

**Possible cause**
Maybe the initial position mouse is wrong (seems to shift down).

**Steps to reproduce**
TESTAR WebDriver protocol:  web_generic
GENERATE mode (SPY mode on): 

"C:\Program Files\Internet Explorer\iexplore.exe" "https://www.symbio6.nl/ou/demo1a"
or
"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" "https://www.symbio6.nl/ou/demo1a"
or demo2e or demo3

The sequence shown on the bottom of the page gives the real clicks made by TESTAR on the web.
The first thing you notice is a preference for the lower action (because the mouse clicks here accidentally)

**Configuration** 

Device

- TESTAR 2.2.3
- Java 11.0.6
- Windows 10 version 1909
- Chrome 80.0.3987.87 (ChromeDriver 80.0.3987.16)
- Explorer 11.0.170
- VirtualBox 6.1.2

 Webpages

- hard coded webpages with basic HTML
- W3C standard (checked with validator.w3.org)
- no css, no script

**Already tested**

- Different actions: links (demo1a – demo1d), submit button (demo2e – demo2h), form dropdown list (demo3, with auto submit)
- Different location actions on webpage
- Different browsers: Chrome, Explorer with end without VirtualBox
- Full and smaller screens
- Other servers / websites
- Reset settings and cache browser
- Window in left up corner screen

**Working correct**
- In SPY mode
- In virtualbox ? But then opening new tabs (filtering not possible) and outside browser window

![Screenshot_mouse_click_not_selected_action](https://user-images.githubusercontent.com/53942605/74160706-18fa2d00-4c1e-11ea-8fc4-f0d5cbfecf75.jpg)

**Comment by ferpasri** [comment]
Hi @Blauwtipje 
Related to: https://github.com/TESTARtool/TESTAR_dev/issues/222

When webdriver actions fail, can you indicate me what are the Windows screen options that are being used in your environment?

Display % ? Is it the recommended one ? Blurry option is enabled ?

**Comment by Blauwtipje** [comment]
Display > Scale and layout = 125%
> Advanced scaling settings > fix scaling for apps: On
(Custom scaling off)

**Comment by pekkakaho** [comment]
@Blauwtipje did you manage to fix this? Was is because of resolution settings or maybe because there was not enough time between actions?

**Comment by Blauwtipje** [comment]
I fix this with the resolution settings of Windows 10, set to 100%.
