### ISSUE TITLE
[Refactor] AbstractID action is not always the same

### ISSUE THREAD

**Issue by Blauwtipje** [TESTARtool/TESTAR_dev#219]
**Description**
Not all hash from same action (abstractID) are equal when page returns to same node (abstractID). 

**Possible cause**
The hash formula is probably not based on stabile factors from the widget tree. In the Explorer example this happens around a drag action (state 12). In Chrome even more hash (from same action) are different.

**Steps to reproduce**
TESTAR WebDriver protocol:  web_generic
GENERATE mode: 
"C:\Program Files\Internet Explorer\iexplore.exe" "https://www.symbio6.nl/ou/demo1a"
or
"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" "https://www.symbio6.nl/ou/demo1a"

**Example reports** (count hash with ctrl F)
[issue_google_action_hash.pdf](https://github.com/TESTARtool/TESTAR_dev/files/4182462/issue_google_action_hash.pdf)
[issue_explorer_action_hash.pdf](https://github.com/TESTARtool/TESTAR_dev/files/4182484/issue_explorer_action_hash.pdf)

**Configuration** 
Device
- TESTAR 2.2.3
- Java 11.0.6
- Windows 10 version 1909
- Chrome 80.0.3987.87 (ChromeDriver 80.0.3987.16)
- Explorer 11.0.170

Webpages
- W3C standard (checked with validator.w3.org)

**Already tested**
Other pages
Different browsers: Chrome and Explorer

**Working correct**
Node hash (abstractID) as expected: the same for all same pages (except the start node in Chrome)
Repeat loading same page: abstractID action is the same

**Comment by pekkakaho** [comment]
The actionID is on our to-be-refactored list.

**Comment by Blauwtipje** [comment]
Okay, thanks

**Comment by ferpasri** [comment]
This issue was fixed for this specific use case. I'm going to close and open a new specific one in #317
