### ISSUE TITLE
More documentation is needed explaining all settings (CLI)

### ISSUE THREAD

**Issue by abons** [TESTARtool/TESTAR_dev#240]
I like working from the Command Line Interface (CLI)
I usually execute these commands from scripts inside a package.json

from the [handson](https://testar.org/images/development/Hands_on_TESTAR_Training_Manual_2020_Feb_5.pdf#page=27) I learned to use settings inside my CL.

The handson also mentions the test.settings file in page 22.
And Fernando showed me the fruit\monkey\ConfigTags.java

But I can't find info explaining what each setting does (CLI/settings docs)

**Comment by ferpasri** [comment]
Created wiki section to comment about TESTAR settings and CLI:
https://github.com/TESTARtool/TESTAR_dev/wiki/TESTAR-Settings

We need to update current HandsOn section "C. Test Setting" and add more information about CLI
https://testar.org/images/development/Hands_on_TESTAR_Training_Manual_2020_October_14.pdf
