### ISSUE TITLE
Release 2.2.14: build.gradle is broken on osx

### ISSUE THREAD

**Issue by odipar** [TESTARtool/TESTAR_dev#253]
The build.gradle file assumes windows cmd.
See:

https://github.com/TESTARtool/TESTAR_dev/blob/f7800391ae2decc1d310d3ff5e635c7000226f51/testar/build.gradle#L312

**Comment by odipar** [comment]
can the gradle task be made conditional (platform specific?)

**Comment by ferpasri** [comment]
Hi Robbert,
`gradle build` and `gradle installdist` are being executed without issues right?

As you said, for now CI gradle tasks from `group = 'test_testar_workflow'` cannot be run on osx.
We can try to check the OS and update these Chromedriver tasks to add specific osx executions (but I don't have a osx environment to test it :D)

**Comment by odipar** [comment]
Unfortunately, `gradle build` and `gradle installDist` execute the `downloadChromedriver` task which belongs to the `group = `test_testar_workflow`. Not sure why that happens?

Another approach would be to make the windows specific tasks depend on the platform (i.e. windows)?

**Comment by ferpasri** [comment]
Reproduced with Linux OS:
- `./gradlew build` should not run this `downloadChromedriver` task
- But there seems to be a gradle evaluation phase that throws: `"cmd": error=2, No such file or directory`

New Branch (issue_253_build) https://github.com/TESTARtool/TESTAR_dev/tree/issue_253_build contains
```
    // Disable for non-Windows environments (Linux, osx)
    if (!System.getProperty('os.name').toLowerCase().contains('windows')) {
        return;
    }
```

If @odipar can confirm that now `gradle build` also works for osx, we can modify and maybe prepare some CI verification (at least that builds for Linux / osx)

**Comment by odipar** [comment]
**Confirmed** - branch `issue_253_build` builds on osx.

**Comment by ferpasri** [comment]
Now it is possible to build TESTAR on Linux and osx without this `cmd` issue.
In the future we will need to improve webdriver CI tasks.
