### ISSUE TITLE
Generic oracle: errors in log files

### ISSUE THREAD

**Issue by matveypashkovskiy** [TESTARtool/TESTAR_dev#272]
During the testing session, TESTAR could poll new lines from log files and take into account standard log file format (for example: [web apps](https://en.wikipedia.org/wiki/Common_Log_Format), [Win apps](https://docs.microsoft.com/en-us/windows/win32/eventlog/querying-for-event-source-messages), [Android apps](https://developer.android.com/studio/debug/am-logcat)) or regexp and identify if errors were raised.

FYI @tatu-aalto, @sorin-patrasoiu

**Comment by pekkakaho** [comment]
There is a related pull request from Sietse #302

**Comment by ferpasri** [comment]
The new LogOracle implementation #302  allows users to specify suspicious regular expressions that should be searched for in specific log files. Currently, the user needs to indicate the static log file name in the TESTAR settings.

To improve this feature, we will track into #271 the extension of this implementation to additionally track the generation of dynamic log files in specific folders.
