### ISSUE TITLE
[Replay mode] When running a second time the test sequence, OrientDB crash

### ISSUE THREAD

**Issue by sorin-patrasoiu** [TESTARtool/TESTAR_dev#274]
**Short description:** When running a second time the test sequence, OrientDB crash

**Environment:**
OS: Windows 10 Enterprise
JDK: jdk1.8.0_202
Memory: 13.7 GB
OrientDB: 3.0.34
TESTAR branch: f-secure_dev
TESTAR version: 2.2.17

**Steps to reproduce:**
- Open TESTAR
- Run one OK sequence in Replay mode and let it finish
- Run same sequence again in Replay mode

**Expected result:** TESTAR sequence is executed
**Actual result:** OrientDB crash with the following error: `java.lang.IllegalStateException: File is allowed to be opened only once`
Full error can be found here: https://testartalk.slack.com/archives/C022DBPUXS7/p1623753607003300

**Comment by ferpasri** [comment]
1. First execution opens a State Model connection (TESTAR initialize), but the Replay mode loop never closes it.
2. Then second execution fails because first one still open.

The correct integration of Replay mode with the State Model inference feature #269 will fix this issue
