### ISSUE TITLE
Ribbon collapse button cannot be filtered out

### ISSUE THREAD

**Issue by digiofficerobin** [TESTARtool/TESTAR_dev#294]
Hi,

I want to filter out the 'Het lint samenvoegen' button in the ribbon, because it collapse the ribbon to a smaller ribbon where I cannot see the buttons on the ribbon anymore. And it is not very useful for my tests.

![image](https://user-images.githubusercontent.com/16424069/152869723-914f6f0a-3509-4036-a84e-c7f891ddd609.png)

![image](https://user-images.githubusercontent.com/16424069/152869961-4a9d9a70-5272-4736-a02c-c0b67762b931.png)

I have tried several properties, but I cannot manage to filter this button out.

![image](https://user-images.githubusercontent.com/16424069/152870115-382978d5-a468-4d5e-b1b4-23a1d4dede40.png)

**Comment by pekkakaho** [comment]
Hi Robin,

I think you do have a grey dot under the green dot, so probably the filtering is working for that widget, but there are 3 other widgets that the 3 green dots are for.

We need to look what the buttons are actually for - you could run generate mode and look from the generated HTML report what action are derive - there should be some info about them.

BR,
-Pekka
