### ISSUE TITLE
Deriving text input actions: replace text vs. append text - 2 different actions?

### ISSUE THREAD

**Issue by pekkakaho** [TESTARtool/TESTAR_dev#311]
Deriving text input actions is currently only creating replace text action (select all, paste or input text to replace the old text).

Append text could be also possible, adding more text into existing text could be another type of action.

**Comment by ferpasri** [comment]
In the proposed protocols, TESTAR allows users to use a boolean variable to choose if they want to perform a typing or pasting action by replacing the existing text or adding the text to the end.

https://github.com/TESTARtool/TESTAR_dev/blob/e978aed623ecb068dba755402065a1b278ae3469/core/src/org/testar/monkey/alayer/actions/StdActionCompiler.java#L251

https://github.com/TESTARtool/TESTAR_dev/blob/e978aed623ecb068dba755402065a1b278ae3469/core/src/org/testar/monkey/alayer/actions/StdActionCompiler.java#L322

For now, we will close this issue and open new and more specific typing issues if needed. For example, the Replacing text action always uses the `Ctrl + A` combination #377 

Or future challenges with action abstraction :)
