### ISSUE TITLE
[Refactor] Reduce the number of protocols

### ISSUE THREAD

**Issue by ferpasri** [TESTARtool/TESTAR_dev#334]
Select and reduce the number of protocols because it can confuse users.

1. Examples of protocols that can go out:
- webdriver_gwt
- Merge desktop_qlearning and desktop_generic_action_selection

2. Add some description to the protocols to pop them up in the GUI.
When the user clicks a question mark button, we will pop up the message.

**Comment by ramondevries** [comment]
We have to take a decision on which protocols to keep.

**Comment by ferpasri** [comment]
1. Check in the STV and IVVES courses the protocols we use for the different lessons.

2. Merge desktop protocols

Move functionality of:
- desktop_generic_all_features
- desktop_generic_json
to **desktop_generic** with some setting or Java variable to enable/disable the JSON printing

- desktop_generic_statemodel
to **desktop_generic** with the setting `StateModelEnabled = false` disabled by default

Merge:
- desktop_generic_action_selection
- desktop_qlearning
- desktop_simple_stategraph
to one protocol like `**desktop_action_selector**` or `desktop_selector`

Check to merge:
- desktop_simple_stategraph_eye
- desktop_simple_stategraph_sikulix
to one protocol like `**desktop_widget_recognition**` or similar

Maintain:
- **desktop_SwingSet2**
