### ISSUE TITLE
[Dependency Bug] TESTAR issue with chromedriver version 111

### ISSUE THREAD

**Issue by ferpasri** [TESTARtool/TESTAR_dev#343]
Seems that the Selenium driver contains a bug with Chrome 111: 
https://github.com/SeleniumHQ/selenium/issues/11750

To fix this issue in TESTAR, we can add the next argument to the ChromeOptions:  

`options.addArguments("--remote-allow-origins=*");`

https://github.com/TESTARtool/TESTAR_dev/blob/00e153ebebb8cc2f69a2824109fac4a4ab055ff6/webdriver/src/org/testar/monkey/alayer/webdriver/WdDriver.java#L157-L180

**Comment by ferpasri** [comment]
Fixed in #340

**Comment by johnqa** [comment]
Would it be possible to have a binary with this fix? Maybe a new release of the software?

**Comment by ferpasri** [comment]
Hi @johnqa , I have created this pre-release:
https://github.com/TESTARtool/TESTAR_dev/releases/tag/pre-v2.6.4

**Comment by johnqa** [comment]
Great, thank you. That fixed my issue.
