### ISSUE TITLE
Chrome download bar affects Webdriver mouse coordinates

### ISSUE THREAD

**Issue by ferpasri** [TESTARtool/TESTAR_dev#365]
### TESTAR Behaviour

TESTAR uses the function ` window.screenY + window.outerHeight - window.innerHeight` to calculate the y-axis location of the window screen on which the SUT web page is located.

https://github.com/TESTARtool/TESTAR_dev/blob/2caac040af4ff5fdcd2261cb6df3cd8b4a6c88f3/webdriver/resources/web-extension/js/testar.canvas.js#L50-L58

![image](https://github.com/TESTARtool/TESTAR_dev/assets/32359126/a6a94324-536b-42e5-8740-4f0db6b8370e)

### Issue

The problem is that the function assumes that the Chrome browser bars, like the Tab bar and URL bars, always start on the top of the browser.  
However, some Chrome bars, such as the Downloads bar, can appear at the bottom of the browser. Something that produces a wrong calculation of the y-axis location of the SUT web page.

https://github.com/TESTARtool/TESTAR_dev/blob/2caac040af4ff5fdcd2261cb6df3cd8b4a6c88f3/webdriver/src/org/testar/monkey/alayer/webdriver/CanvasDimensions.java#L103-L104

![image](https://github.com/TESTARtool/TESTAR_dev/assets/32359126/5bc5b07c-d6cb-40b9-9b28-1ca118176869)

This provokes the [WdMouse](https://github.com/TESTARtool/TESTAR_dev/blob/master/webdriver/src/org/testar/monkey/alayer/webdriver/WdMouse.java) to wrongly try to obtain the position of the cursor and wrongly try to move the cursor to click web elements. 

https://github.com/TESTARtool/TESTAR_dev/blob/2caac040af4ff5fdcd2261cb6df3cd8b4a6c88f3/webdriver/src/org/testar/monkey/alayer/webdriver/WdMouse.java#L99
https://github.com/TESTARtool/TESTAR_dev/blob/2caac040af4ff5fdcd2261cb6df3cd8b4a6c88f3/webdriver/src/org/testar/monkey/alayer/webdriver/WdMouse.java#L115

### Possible solutions

1. Disable the download bar or change to another Chrome option like `chrome://flags/#download-bubble`, which does not open the bottom bar in the browser.
2. Fix the Javascript calculation to correctly calculate the y-axis location of the web SUT on the screen.

**Comment by ferpasri** [comment]
It seems that the download bubble has been the default Chrome option since August 2023.

**Comment by ramondevries** [comment]
In newer version (>= 117) of chrome the download bar is replaced with a bubble icon. closing, wil not fix for now.
