### ISSUE TITLE
Add a regular expressions syntax checker

### ISSUE THREAD

**Issue by tanjavos** [TESTARtool/TESTAR_dev#62]
This way invalid regular expressions are not accepted through the dialog. Now what happens is that no warning whatsoever is given and TESTAR just does not apply it.

**Comment by ferpasri** [comment]
- [X] Regular expressions are checked through the TESTAR SettingsDialog.
- [ ] But not if TESTAR is executed disabling the GUI.

https://github.com/TESTARtool/TESTAR_dev/blob/6007a958999dca3ec724771b6157c119786c691c/testar/src/org/testar/settingsdialog/SettingsDialog.java#L157-L187

![image](https://user-images.githubusercontent.com/32359126/208482962-3af7b35a-7b35-4274-a746-ae6661b631f7.png)
![image](https://user-images.githubusercontent.com/32359126/208483002-63fd6c85-0d84-49a2-bfe3-e397e784fbd8.png)
