### ISSUE TITLE
Add a Listener that enables TESTAR to listen to the StdOut/Err SUT

### ISSUE THREAD

**Issue by tanjavos** [TESTARtool/TESTAR_dev#63]
It should be able to listen during testing (ONLINE oracle) and it should stores it all in a file that can be inspected after testing (OFFLINE oracle).

System.out and System.err listens to the StdOut/Err of TESTAR itself. We should somehow catch the StdOUT/ERR of the SUT when it is started up.

HINTS on a possible solution within Java:  https://stackoverflow.com/questions/3643939/java-process-with-input-output-stream

HINTS on a possible solution in cpp WinAPI:
https://msdn.microsoft.com/en-us/library/windows/desktop/ms682425(v=vs.85).aspx

https://msdn.microsoft.com/en-us/library/windows/desktop/ms682499(v=vs.85).aspx

**Comment by ferpasri** [comment]
Implemented, lets close this enhancement thread.
If some issues / idea exists in the future, we will reopen or create new one.
