### ISSUE TITLE
Handling multiple SUT processes

### ISSUE THREAD

**Issue by pekkakaho** [TESTARtool/TESTAR_dev#68]
Happened with IE but not with Chrome:

SUT has a modal popup that is another process, and TESTAR tries to bring original process to foreground and that does not work because of modal popup.

**Comment by ferpasri** [comment]
The `SUTProcesses` setting has been refactored to allow the connection with multi-processes SUTs #388 

The TESTAR user can indicate with regular expressions which processes conform to the SUT

https://github.com/TESTARtool/TESTAR_dev/wiki/3-TESTAR-configuration-and-settings#connect-with-a-multi-processes-sut-advanced-dialog

![image](https://github.com/TESTARtool/TESTAR_dev/assets/32359126/3894f5d8-8edd-4795-ae80-90f88b1b4ded)
