### ISSUE TITLE
The  Abstract Action ID is not derived from  the Abstract State ID, but from  the Concrete State ID.

### ISSUE THREAD

**Issue by carlosengers** [TESTARtool/TESTAR_dev#80]
For an experiment, to observe execution traces for temporal behavior (e.g. 'eventually'),  I created a  very simple java application: a single window java application that simulates a stack with a depth of 7.
I deliberately wanted to limit the actions to 'control' TESTAR.

![2018-06-05_simple stacker](https://user-images.githubusercontent.com/35034352/40965542-4991417e-68ae-11e8-9747-26da1ada92da.png)

When inspecting the log,  i noticed that the abstract ID's of the executed Actions showed up  in the output (logs, XML, .DOT)

 conforming to the TESTAR_manual 1.3  page 51:

> - Concrete
>  Action ID: the ID for an action a in state s is calculated as id(a) =f(id(s) + p1 + … + pk) where pi are the action properties.
>  - Abstract
>  Action ID: similar to the concrete action ID, but discarding properties of the action (e.g. texts typed, keys pressed). For example, we can refer to writing in a  concrete textbox, no matter of the text used to write
> 

![2018-05-06 action id difference](https://user-images.githubusercontent.com/35034352/40965561-548ef85a-68ae-11e8-8514-4782e31d9d31.png)

In other words: Abstract ID's for actions are derived from the concrete state id. This functionality is implemented in TESTAR. So, this is by design and as such this is not a code bug. 

![2018-05-06 action id assignment in sourcecode](https://user-images.githubusercontent.com/35034352/40965572-5be733b0-68ae-11e8-9096-72a817155ea7.png)

However, i would have expected that an abstract action-id would be derived from the abstract state-id. Comparable to the way  an abstract state is derived from the abstract widget tree.
The current implementation does not condense the number of actions when they are abstracted, which is usually a reason for applying abstraction.
( see 
[AbstractActions 20180529 CSS.pdf](https://github.com/TESTARtool/TESTAR_dev/files/2071555/AbstractActions.20180529.CSS.pdf)
)

Is this worth changing?

**Comment by pekkakaho** [comment]
you can use abstractIDCustom instead
