### ISSUE TITLE
TESTAR with Java JDK 10/11/12 enviroment

### ISSUE THREAD

**Issue by ferpasri** [TESTARtool/TESTAR_dev#97]
Study the benefits of the Java 9 ,10 and 11 environments in relation to TESTAR.
Prepare an execution environment and perform compilation + execution tests.

UPDATE:
- Branch "testar_new_jdk" allows the compilation "gradlew installdist" and execution of TESTAR into a VM with Java JDK12.
https://github.com/TESTARtool/TESTAR_dev/commit/c7d480addd3b47de8f6eeafac5c68081ab6f3978

- [ OK ] Compiles and allow the execution of Notepad + Windows UIAutomation
- [ OK ] Compiles and allow the execution of Calculator.jar + Windows UIAutomation

- [ Swing ERROR Temporally SOLVED]  https://github.com/TESTARtool/TESTAR_dev/commit/c11ee17f22070cb17c14523c1d0ed5ff25878362
 Access Bridge method:
Windows.GetHWNDFromAccessibleContext(vmidAC[0],vmidAC[1]);

**Comment by mdeiman** [comment]
We are now on Java 12. Can we give it some prio?
Testar needs Java 8 now...

**Comment by ferpasri** [comment]
Installed java 12 JDK :

Into windows/native_src/Makefile_w10, we're using into compilation:
`javah -jni -force -o windows.h -classpath ..\target\classes\java\main $(JAVA_CLASS)`

- Issue with gradlew compilation:
'javah' is not recognized as an internal or external command.

javah was removed since Java 10, http://openjdk.java.net/jeps/313

At least a new branch and TESTAR version will be needed:
https://github.com/TESTARtool/TESTAR_dev/tree/testar_new_jdk

**Comment by ferpasri** [comment]
Related question:
https://stackoverflow.com/questions/48816188/kotlin-replacement-for-javah

The problem is, javah operates on compiled .class files, while javac operates on source files (i.e.  .java files.)

**Comment by ferpasri** [comment]
We have a TODO task:
- We need the Java 8 JDK to compile the protocols, and we were thinking about allow the TESTAR execution if the users have the JAVA_HOME defined into the JRE instead the JDK.
- Since Java 10, JDK and JRE are no more separated into two distributions. Now all Java package is a JDK with the compilation tools.
- Should we include here the discussion?

**Comment by ferpasri** [comment]
Java Swing version problems (Access Bridge??)
- Normal cmd:  **java -jar suts\SwingSet2.jar** opens the application with a warning
- TESTAR cmd: **java -jar suts\SwingSet2.jar** opens the application with a warning, and then throws the Runtime Java Error

Is this an error about the access of Java Access Bridge ??

https://stackoverflow.com/questions/50251798/what-is-an-illegal-reflective-access
https://stackoverflow.com/questions/50251798/what-is-an-illegal-reflective-access/50251958#50251958

**Comment by ferpasri** [comment]
[hs_err_pid5800.log](https://github.com/TESTARtool/TESTAR_dev/files/3406207/hs_err_pid5800.log)

stack at sp + 7 slots: {method} {0x000001ca2f79f2c8} 'getAccessibleHypertext' '(Ljavax/accessibility/AccessibleContext;)Ljavax/accessibility/AccessibleHypertext;' in 'com/sun/java/accessibility/internal/AccessBridge'

**Comment by carlosengers** [comment]
Consider the following modification/workaround in Makefile_w10 and openjdk 13 installed.
This works for me. (using  IDEA intellij )  
only cavea till now: windows.h isn't automatically deleted on rebuild. you need to perform the GRADLE clean task before.



`JAVA_CLASSFILE = "..\target\classes\java\main\org\fruit\alayer\windows\Windows.class"
# up to jdk 8:
JAVA_CLASS = org.fruit.alayer.windows.Windows
# > jdk 8:
JAVA_SOURCE = ..\src\org\fruit\alayer\windows\Windows.java

OBJFILES= main_w10.obj\
# by urueda
		  AccessBridgeCalls.obj

HPPFILES= windows.h\


CPPFLAGS= /EHsc /O2 /MD /wd4311 /wd4312


all: windows.h $(DLLFILE)

windows.h: $(JAVA_CLASSFILE)
#requires jdk 8
#    javah -jni -force -o windows.h -classpath ..\target\classes\java\main $(JAVA_CLASS)
#requires jdk >8 CSS 20200405
     javac -h  tmp -classpath  .;..\target\classes\java\main\;..\..\core\target\classes\java\main  $(JAVA_SOURCE)
     move tmp\*.h .
     rename org*.h windows.h
     RD /S /Q  tmp

$(OBJFILES): windows.h`

**Comment by rneeft** [comment]
The JAVA_SOURCE is outdated: correct line must be:

```
JAVA_SOURCE = ..\src\org\testar\monkey\alayer\windows\Windows.java
```

**Comment by ferpasri** [comment]
TESTAR works with Java 8, 11 and 17
